version: '4'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=crypto
      - MYSQL_ROOT_PASSWORD=root